language: node_js
os: linux
dist: xenial
node_js:
- node
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_d5808b310a6d_key -iv $encrypted_d5808b310a6d_iv
  -in gae-client-secret.json.enc -out gae-client-secret.json -d
- rm package-lock.json
before_script:
- npm install -g @angular/cli
script:
- npm run build:ssr

# Dumb workaround because GAE always runs npm install :)
before_deploy:
- rm package-lock.json
- rm package.json
- mv app-engine-package.json
deploy:
  skip_cleanup: true
  provider: gae
  keyfile: gae-client-secret.json
  project: images-chu-mk
  on:
    branch: feature/server-side-rendering
