language: node_js
os: linux
dist: xenial
node_js:
  - "node"
cache:
  directories:
  - "node_modules"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  # This prevents npm ci from running and deleting all the cached modules
  - rm package-lock.json
before_script:
  - npm install -g @angular/cli
script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
  - ng build --prod
# before_deploy:
#   - npm install -g firebase-tools
# deploy:
#   cleanup: false
#   provider: script
#   script: firebase deploy --token ${FIREBASE_TOKEN}
deploy:
  provider: firebase
  token: ${FIREBASE_TOKEN}
  edge: true