language: node_js
node_js:
  - "node"
cache: npm
sudo: required
install:
  - npm install -g @angular/cli
script:
  - ng build --prod
before_deploy:
  - npm install -g firebase-tools
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: ${FIREBASE_TOKEN}