language: node_js
os: linux
dist: xenial
node_js:
  - "node"
cache:
  directories:
  - "node_modules"

before_install:
  # This prevents npm ci from running and deleting all the cached modules
  - rm package-lock.json
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod
# before_deploy:
#   - npm install -g firebase-tools
# deploy:
#   cleanup: false
#   provider: script
#   script: firebase deploy --token ${FIREBASE_TOKEN}
deploy:
  provider: firebase
  token: ${FIREBASE_TOKEN}
  edge: true