language: node_js
node_js:
  - "node"
cache: npm
sudo: required
before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
script:
  - ng build --prod
deploy:
  skip_cleanup: true
  provider: script
  script: firebase deploy --token ${FIREBASE_TOKEN}