language: node_js
os: linux
dist: xenial
node_js:
  - "node"
cache:
  directories:
  - "node_modules"

addons:
  chrome: stable

before_install:
  # This prevents npm ci from running and deleting all the cached modules
  - rm package-lock.json
before_script:
  - npm install -g @angular/cli
script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
  - ng build --prod
deploy:
  provider: firebase
  token: ${FIREBASE_TOKEN}
  edge: true