name: Docker Build and Push
on:
  push:
#      branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
    name: Publish Docker Container
    runs-on: ubuntu-latest
    steps:
      - uses: nelonoel/branch-name@v1
        name: Set Branch Name in Environment Variable
        
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: whoan/docker-build-with-cache-action@v5
        name: Build, Cache and Push Docker Image
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
          image_tag: ${BRANCH_NAME}
          image_name: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}
          
          push_image_and_stages: docker run ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${BRANCH_NAME}
